language: node_js
node_js:
  - 8
script: npm test -- --runInBand
after_success:
  - npm run codecov
  - "if [ $TRAVIS_EVENT_TYPE = 'push' ]
    then
      npm run chromatic -- --app-code=$CHROMATIC_APPCODE
    fi"
before_deploy:
  - cd docs
  - npm install
  - npm run build
  - touch out/.nojekyll
  - npm run storybook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: docs/out
  on:
    branch: master
