language: node_js
node_js:
  - 10
before_script: npm run bootstrap
after_success:
  - npm run coverage
  - npm run codecov
before_deploy:
  - cd docs
  - npm install
  - npm run build
  - touch out/.nojekyll
  - cd ..
  - npm run storybook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: docs/out
  on:
    branch: master
