name: Create a new GitHub release for a package

on:
  workflow_dispatch:
    inputs:
      versionTag:
        required: true
        description: 'Tag for the new release'
      packageName:
        required: true
        description: 'Name of package being released'

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  create-release:
    # Name the Job
    name: Create GitHub release
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PNPM cache via actions/cache@v2
        id: pnpm-cache
        uses: actions/cache@v2
        with:
          path: /home/runner/work/design-system/design-system/common/temp/pnpm-store/v3
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: node common/scripts/install-run-rush.js install

      # TODO convert release note tool to auto-installer so we don't have to do full build
      - name: Build components
        run: node common/scripts/install-run-rush.js build

      - name: Create release notes
        run: |
          node common/scripts/install-run-rush.js create-release-notes --package-name ${{ github.event.inputs.packageName }}

      #      - name: NPM Publish
      #        run: |
      #          node common/scripts/install-run-rush.js publish -p --include-all --npm-auth-token="${{ secrets.NPM_TOKEN }}"

      - name: 'Create Release'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: ./RELEASE_NOTES.md
          name: '${{ github.event.inputs.packageName }} ${{ github.event.inputs.versionTag }}'
          tag_name: ${{ github.event.inputs.versionTag }}
